### ISSUE TITLE
Required Video select option coming even if there is no video seen by that person

### ISSUE THREAD

**Issue by lokeshgarg92** [digitalgreenorg/dg#363]
Steps to reproduce
1. Login with laxmch account
2. Fill the entries as follows:
a. Bommanachervu
b. Y. Lakshmi
c. Group - 2nd option
d. Person - 9th option
Swipe next twice 
Page asking for video comes with no options and user is unable to move forward because there is no video seen by this person

Expected Output
Come appropriate message should come such that user gets notified that another person should be selected

Actual Output
Sorry, this field is required comes up.

**Comment by jahnavik** [comment]
fixed
