### ISSUE TITLE
Existing data gets erased from Screening form if any extra person and group is added

### ISSUE THREAD

**Issue by lokeshgarg92** [digitalgreenorg/dg#377]
Steps to reproduce
1. Edit Screening
2. Add any extra group apart from the existing one

Actual Output
1. Expressed adopted video field becomes empty
2. Interested check boxes get unchecked

Expected Output
1. Expressed adopted video should remain unchanged and should not become empty
2. Interested checkboxes should also remain as it is

**Comment by abhishekchandran** [comment]
Interested and expressed adoption video fields removed, due to change in forms
