### ISSUE TITLE
Video not relevant to the topic

### ISSUE THREAD

**Issue by lokeshgarg92** [digitalgreenorg/dg#414]
BLACK GRAM
1. CLICKED ON THE TITE OF THE VIDEO
2. SUB-OPTIONS APPEARED
3. PRE-SOWING
    3.1FIELD PREPARATION (NO VIDEO FOUND)
    3.2SEED SELECTION (NO VIDEO FOUND)
    3.3SEED GERMINATION TEST (NO VIDEO FOUND)
    3.4SEED TREATMENT (NO VIDEO FOUND)
4. SOWING AND CROP MANAGEMENT
    4.1INTERCULTURE
        4.1.1 HAND WEEDING(NO VIDEO FOUND)
        4.1.2 MECHNAICAL WEEDING(NO VIDEO FOUND)
        4.1.3 CHEMICAL WEEDICIDE(NO VIDEO FOUND)
        4.1.4 EARTHING UP(NO VIDEO FOUND)
        4.1.5 NIPPING(NO VIDEO FOUND)
    4.2 IRRIGATION
    4.3 SOWING
    4.4 NUTRIENT MANGAMENT 
    4.5 DISEASE AND PEST CONTROL 
5. HARVESTING
    5.1 HAREVSTING
    5.2 POST HARVESTING 
6. SUCCESS STORY
    6.1 SPRAYING OF PESTICIDE ON BLACK GRAM 
    http://www.digitalgreen.org/agri/opt/?crop=16&time=4&level=
(video not relevant to the topic)

**Comment by jahnavik** [comment]
Link doesn't exist
