### ISSUE TITLE
Error message 'Import Error' at coco site

### ISSUE THREAD

**Issue by sauravpratihar** [digitalgreenorg/dg#445]
in ' http://www.digitalgreen.org/tools/ ' the link 'Click here' under "Try COCO today!" Cation is not working. you sholud change it to "http://www.digitalgreen.org/coco/#login"

**Comment by aadish** [comment]
Hi Saurav 
Thanks for showing interest in COCO

Please use sandbox.digitagreen,org/coco for the demo purpose and please try checking click here again it should take you to above said url and the username and password provided will work

**Comment by sauravpratihar** [comment]
Yes ! it work now ..
