### ISSUE TITLE
Upload tool bug bash

### ISSUE THREAD

**Issue by proviveknayan** [digitalgreenorg/dg#699]
#684 
--Spelling
Group form: video to Video
Screening form: mediator to Mediator

--Translation
Hindi: डाटा डाउनलोड करें
French: Télécharger des données

--Functionality
a. Once export/import is done, user has to logout and login to syn to the latest db. This should be easier for the user. Either syncing to latest db from within COCO or a notification on what s/he need to do next.
b. User should be notified if s/he tries to upload the same export file more than once
c. We can authorize the upload page only to certain users
d. Adoption data is not being uploaded
e. Person in a group get assigned to a random group prgudem-1 after data file upload and logout/login
f. Error page on other file extension upload
g. Can we position export data button somewhere less prominent?

**Comment by djangobotpython** [comment]
User should be notified if s/he tries to upload the same export file more than once
This has been
